# Generated by Django 3.1.6 on 2021-02-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210218_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hire_date',
            field=models.DateField(null=True),
        ),
    ]
