# Generated by Django 3.1.5 on 2021-01-30 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_code', models.CharField(max_length=12, unique=True)),
                ('Box_status', models.PositiveSmallIntegerField(choices=[(1, 'Free'), (2, 'Busy')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_type', models.PositiveSmallIntegerField(choices=[(1, 'Sedan'), (2, 'Jip'), (3, 'Mini'), (4, 'Tax')], default=1, verbose_name='CarType')),
                ('cars_model', models.PositiveSmallIntegerField(choices=[(1, 'Mercedes'), (2, 'BMW'), (3, 'Lexus'), (4, 'Kia'), (5, 'Subaru'), (6, 'Mazda'), (7, 'Skoda'), (8, 'Toyota'), (9, 'Honda'), (10, 'Peugeot'), (11, 'Volvo')], default=1, verbose_name='CarType')),
                ('cars_number', models.CharField(default='BMW-111', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=11, unique=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='washers', to='wellwash.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(verbose_name='Order time')),
                ('start_time', models.DateTimeField(blank=True, verbose_name='Begin time')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='End time')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ordered'), (2, 'Process'), (3, 'Closed')])),
                ('box_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='wellwash.box')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='wellwash.car')),
                ('washer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='wellwash.washer')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='location_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='branch', to='wellwash.location'),
        ),
        migrations.AddField(
            model_name='box',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='wellwash.branch'),
        ),
    ]
