# Generated by Django 3.1.5 on 2021-02-04 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_code', models.CharField(max_length=12, unique=True)),
                ('box_status', models.CharField(choices=[('F', 'Free'), ('B', 'Busy')], default='F', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_model', models.PositiveSmallIntegerField(choices=[(1, 'Mercedes'), (2, 'BMW'), (3, 'Lexus'), (4, 'Kia'), (5, 'Subaru'), (6, 'Mazda'), (7, 'Skoda'), (8, 'Toyota'), (9, 'Honda'), (10, 'Peugeot'), (11, 'Volvo')], default=1, verbose_name='CarModel')),
                ('licence_plate', models.CharField(default='CAR-001', max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('SE', 'Sedan'), ('JI', 'Jip'), ('MI', 'Mini'), ('TA', 'Taxi')], default='SE', max_length=2, unique=True, verbose_name='Car Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Coupon Expiration Date')),
                ('discount', models.IntegerField(help_text='%', verbose_name='Discount')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('car_plate', models.CharField(max_length=20, verbose_name="Car's license plate")),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='WashType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Car Type')),
                ('percentage', models.IntegerField(default=100, verbose_name='Percentage of base price')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Price')),
                ('my_wash_price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Price')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='Order time')),
                ('start_time', models.DateTimeField(null=True, verbose_name='Begin time')),
                ('end_time', models.DateTimeField(null=True, verbose_name='End time')),
                ('status', models.PositiveSmallIntegerField(choices=[('ordered', 'Ordered'), ('process', 'Process'), ('closed', 'Closed')])),
                ('box_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='wellwash.box')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='wellwash.car')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='wellwash.coupon')),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('wash_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='wellwash.washtype')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='wellwash.cartype'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('location_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='branch', to='wellwash.location')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='wellwash.branch'),
        ),
    ]
