# Generated by Django 3.1.5 on 2021-02-03 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_code', models.CharField(max_length=12, unique=True)),
                ('box_status', models.CharField(choices=[('F', 'Free'), ('B', 'Busy')], default='F', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_model', models.PositiveSmallIntegerField(choices=[(1, 'Mercedes'), (2, 'BMW'), (3, 'Lexus'), (4, 'Kia'), (5, 'Subaru'), (6, 'Mazda'), (7, 'Skoda'), (8, 'Toyota'), (9, 'Honda'), (10, 'Peugeot'), (11, 'Volvo')], default=1, verbose_name='CarModel')),
                ('cars_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Jip', 'Jip'), ('Mini', 'Mini'), ('Tax', 'Tax')], default='Sedan', max_length=10, verbose_name='CarType')),
                ('licence_plate', models.CharField(default='BMW-111', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Coupon Expiration Date')),
                ('discount', models.IntegerField(help_text='%', verbose_name='Discount')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('car_plate', models.CharField(max_length=20, verbose_name="Car's license plate")),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=11, unique=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='washers', to='wellwash.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(verbose_name='Order time')),
                ('start_time', models.DateTimeField(null=True, verbose_name='Begin time')),
                ('end_time', models.DateTimeField(null=True, verbose_name='End time')),
                ('status', models.PositiveSmallIntegerField(choices=[('ordered', 'Ordered'), ('process', 'Process'), ('closed', 'Closed')])),
                ('box_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='wellwash.box')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='wellwash.car')),
                ('washer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='wellwash.washer')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='location_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='branch', to='wellwash.location'),
        ),
        migrations.AddField(
            model_name='box',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='wellwash.branch'),
        ),
    ]
