# Generated by Django 3.1.5 on 2021-02-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='box_id',
            new_name='box',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
