# Generated by Django 3.1.5 on 2021-01-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='Begin time'),
        ),
    ]
