# Generated by Django 3.1.5 on 2021-01-28 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washbox',
            name='wash_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giorgi', to='wellwash.washobject'),
        ),
    ]
