# Generated by Django 3.1.5 on 2021-02-01 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0002_auto_20210130_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='Box_status',
            new_name='box_status',
        ),
    ]
