# Generated by Django 3.1.5 on 2021-01-28 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0002_auto_20210128_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order time'),
            preserve_default=False,
        ),
    ]
