# Generated by Django 3.1.5 on 2021-02-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0002_auto_20210207_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cars_model',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mercedes'), (2, 'BMW'), (3, 'Lexus'), (4, 'Kia'), (5, 'Subaru'), (6, 'Mazda'), (7, 'Skoda'), (8, 'Toyota'), (9, 'Honda'), (10, 'Peugeot'), (11, 'Volvo')], default=1, verbose_name='Car Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='licence_plate',
            field=models.CharField(default='CAR-000', max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='car_type',
            field=models.CharField(choices=[('SE', 'Sedan'), ('JI', 'Jip'), ('MI', 'Mini'), ('TA', 'Taxi'), ('OT', 'Other')], default='SE', max_length=2, unique=True, verbose_name='Car Type'),
        ),
    ]
