# Generated by Django 3.1.5 on 2021-02-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0003_auto_20210207_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('process', 'Process'), ('closed', 'Closed')], default='ordered', max_length=24),
        ),
        migrations.AlterField(
            model_name='washtype',
            name='name',
            field=models.CharField(max_length=12, unique=True, verbose_name='Wash Type'),
        ),
    ]
