# Generated by Django 3.1.5 on 2021-01-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0004_auto_20210128_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='washing_box',
            new_name='box_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='washing_car',
            new_name='car_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='washer',
            new_name='washer_id',
        ),
        migrations.AlterField(
            model_name='cars',
            name='cars_model',
            field=models.CharField(default='BMW', max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='cars_number',
            field=models.CharField(default='BMW-111', max_length=255, unique=True),
        ),
    ]
