# Generated by Django 3.1.5 on 2021-02-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0004_auto_20210202_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Coupon Expiration Date')),
                ('discount', models.IntegerField(help_text='%', verbose_name='Discount')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('car_plate', models.CharField(max_length=20, verbose_name="Car's license plate")),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.AlterField(
            model_name='box',
            name='box_status',
            field=models.CharField(choices=[('F', 'Free'), ('B', 'Busy')], default='F', max_length=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='cars_type',
            field=models.PositiveSmallIntegerField(choices=[('Sedan', 'Sedan'), ('2', 'Jip'), ('3', 'Mini'), ('4', 'Tax')], default='Sedan', verbose_name='CarType'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('ordered', 'Ordered'), ('process', 'Process'), ('closed', 'Closed')]),
        ),
    ]
