# Generated by Django 3.1.5 on 2021-02-07 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0004_auto_20210207_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_car', to='wellwash.cartype'),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='PRice'),
        ),
    ]
