# Generated by Django 3.1.5 on 2021-01-28 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0005_auto_20210128_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='box_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='wellwash.washbox'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='wellwash.cars'),
        ),
        migrations.AlterField(
            model_name='order',
            name='washer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='wellwash.washwasher'),
        ),
    ]
