# Generated by Django 3.1.5 on 2021-02-10 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0006_auto_20210210_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='car_plate',
        ),
        migrations.AddField(
            model_name='coupon',
            name='car_plate_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='wellwash.car'),
        ),
    ]
