# Generated by Django 3.1.5 on 2021-02-10 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0007_auto_20210210_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='car_plate_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coupon', to='wellwash.car'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='quantity',
            field=models.IntegerField(default=4, verbose_name='Quantity'),
        ),
    ]
