# Generated by Django 3.1.5 on 2021-02-10 22:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0009_auto_20210210_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='activate_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 22, 33, 22, 649071, tzinfo=utc), verbose_name='Activate date'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='b0001', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='quantity',
            field=models.IntegerField(default=5, verbose_name='Quantity'),
        ),
    ]
