# Generated by Django 3.1.5 on 2021-02-10 22:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0010_auto_20210210_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='activate_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 22, 39, 53, 746273, tzinfo=utc), verbose_name='Activate date'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
