# Generated by Django 3.1.5 on 2021-02-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0013_auto_20210211_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='car_plate_id',
            new_name='car_plate',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('oordered', 'Ordered'), ('pprocess', 'Process'), ('cclosed', 'Closed')], default='oordered', max_length=24),
        ),
    ]
