# Generated by Django 3.1.6 on 2021-02-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellwash', '0016_auto_20210214_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name': 'Box', 'verbose_name_plural': 'Boxes'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
    ]
